#!/usr/bin/env node

/**
 * Image Processing Pipeline
 * ==========================
 * Takes source images and prepares them for the website:
 *   - Copies to public/images/
 *   - Generates responsive WebP variants in public/images/responsive/
 *   - Updates gallery content file with correct paths
 *
 * Requires: sharp (install with: npm install sharp)
 * Falls back gracefully if sharp is not available.
 *
 * Usage:
 *   node scripts/process-images.mjs <source-folder>
 *   node scripts/process-images.mjs ./content/images
 */

import { readdirSync, copyFileSync, mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, extname, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const PUBLIC_IMAGES = join(PROJECT_ROOT, 'public', 'images');
const RESPONSIVE_DIR = join(PUBLIC_IMAGES, 'responsive');
const GALLERY_FILE = join(PROJECT_ROOT, 'src', 'data', 'content', 'gallery.ts');

const SUPPORTED = ['.jpg', '.jpeg', '.png', '.webp', '.avif'];
const RESPONSIVE_WIDTHS = [480, 768, 1080, 1536];

async function main() {
  const sourceDir = process.argv[2];

  if (!sourceDir || process.argv.includes('--help') || process.argv.includes('-h')) {
    console.log(`
Usage: node scripts/process-images.mjs <source-folder>

Arguments:
  <source-folder>   Path to folder containing source images

The script:
  1. Copies images to public/images/
  2. Generates WebP responsive variants in public/images/responsive/
  3. Updates src/data/content/gallery.ts with the correct paths

Requires 'sharp' for WebP generation. Install with:
  npm install sharp
`);
    process.exit(sourceDir ? 0 : 1);
  }

  if (!existsSync(sourceDir)) {
    console.error(`Error: Source folder not found: ${sourceDir}`);
    process.exit(1);
  }

  const files = readdirSync(sourceDir).filter((f) =>
    SUPPORTED.includes(extname(f).toLowerCase()),
  );

  if (files.length === 0) {
    console.log(`No supported images found in ${sourceDir}`);
    console.log(`Supported formats: ${SUPPORTED.join(', ')}`);
    process.exit(0);
  }

  console.log(`Found ${files.length} image(s) in ${sourceDir}`);

  // Ensure output directories exist
  if (!existsSync(PUBLIC_IMAGES)) mkdirSync(PUBLIC_IMAGES, { recursive: true });
  if (!existsSync(RESPONSIVE_DIR)) mkdirSync(RESPONSIVE_DIR, { recursive: true });

  let sharp;
  try {
    sharp = (await import('sharp')).default;
    console.log('  sharp available — generating WebP responsive variants');
  } catch {
    console.log('  sharp not installed — copying originals only');
    console.log('  Install sharp for WebP generation: npm install sharp');
  }

  const galleryImages = [];

  for (const file of files) {
    const srcPath = join(sourceDir, file);
    const name = basename(file, extname(file));
    const destName = `${name}${extname(file)}`;
    const destPath = join(PUBLIC_IMAGES, destName);

    copyFileSync(srcPath, destPath);
    console.log(`  ✓ Copied ${destName}`);

    // Generate WebP responsive variants if sharp is available
    if (sharp) {
      try {
        for (const width of RESPONSIVE_WIDTHS) {
          const webpPath = join(RESPONSIVE_DIR, `${name}-${width}w.webp`);
          await sharp(srcPath)
            .resize(width)
            .webp({ quality: 80 })
            .toFile(webpPath);
        }
        console.log(`  ✓ Generated responsive WebP variants for ${name}`);
      } catch (err) {
        console.log(`  ⚠ Failed to generate WebP for ${name}: ${err.message}`);
      }
    }

    galleryImages.push({
      src: `/images/${destName}`,
      alt: name.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    });
  }

  // Update gallery content file
  if (galleryImages.length > 0) {
    const out = `// Auto-generated by scripts/process-images.mjs
// Edit to update image paths or alt text.

export interface GalleryImage {
  src: string;
  alt: string;
}

export const galleryImages: GalleryImage[] = ${JSON.stringify(galleryImages, null, 2)};
`;
    writeFileSync(GALLERY_FILE, out, 'utf-8');
    console.log(`  ✓ Updated ${GALLERY_FILE} with ${galleryImages.length} image(s)`);
  }

  console.log('\n✓ Image processing complete!');
  console.log('  Run: npm run dev  or  npm run build\n');
}

main().catch((err) => {
  console.error('Image processing failed:', err);
  process.exit(1);
});
